name: API Tests Newman

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 8 * * *" # Tous les jours Ã  8h

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Installation des librairies
        run: npm install

      - name: Lancement du serveur
        run: |
          nohup node server.js > server.log 2>&1 &
          sleep 5

      - name: Installation de newman + HTML extra reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Lancement de newman
        run: |
          newman run "./postman/collection.postman_collection.json" \
          -e "./postman/environnement.postman_environment.json" \
          --iteration-data "./postman/iteration.json"
